spring:
  config:
    import: application-secret.yml
  application:
    name: budgetManagement

  datasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          timeout: 30000
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: ${server.port}
  servlet:
    context-path: /api
